networks:
  edge:
    driver: bridge
  internal:
    driver: bridge

services:
  eureka:
    build:
      context: .
      dockerfile: ./eureka/Dockerfile
    image: local/eureka-server:dev
    container_name: eureka
    environment:
      - EUREKA_HOST=eureka
      - EUREKA_PORT=8761
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - internal

  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    image: local/api-gateway:dev
    container_name: gateway
    environment:
      - EUREKA_HOST=eureka
      - EUREKA_PORT=8761
      - GATEWAY_PORT=${GATEWAY_PORT-8080}
      - GATEWAY_RL_CAPACITY=${GATEWAY_RL_CAPACITY-20}
      - GATEWAY_RL_REFILL_TOKENS=${GATEWAY_RL_REFILL_TOKENS-20}
      - GATEWAY_RL_REFILL_DURATION=${GATEWAY_RL_REFILL_DURATION-1s}
    depends_on:
      eureka:
        condition: service_healthy
    ports:
      - "${GATEWAY_PORT-8080}:8080"
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - internal
      - edge

  product-service:
    build:
      context: .
      dockerfile: ./product-service/Dockerfile
    image: local/product-service:dev
    container_name: product-service
    environment:
      - EUREKA_HOST=eureka
      - EUREKA_PORT=8761
      - PRODUCT_SERVICE_PORT=8082
      - EUREKA_INSTANCE_HOSTNAME=product-service
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    depends_on:
      eureka:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost:8082/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - internal

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    image: local/api-service:dev
    container_name: api
    environment:
      - EUREKA_HOST=eureka
      - EUREKA_PORT=8761
      - API_PORT=8081
      - JWT_SECRET=${JWT_SECRET}
      - EUREKA_INSTANCE_HOSTNAME=api
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    depends_on:
      eureka:
        condition: service_healthy
      product-service:
        condition: service_started
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost:8081/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - internal
